FROM mcr.microsoft.com/playwright:v1.44-jammy

ENV CI true
WORKDIR /frontend

COPY ./package.json ./pnpm-workspace.yaml ./pnpm-lock.yaml /frontend/
COPY ./e2e/package.json /frontend/e2e/
RUN corepack enable && corepack prepare pnpm@7.33.6 --activate && pnpm install

COPY ./e2e/playwright.config.ts /frontend/e2e/
COPY ./e2e/tests /frontend/e2e/tests/

WORKDIR /frontend/e2e

CMD pnpm test
