# compose file for local development
# starts backend on 8080 with basic auth "dev:password" and Dev oauth2 provider on port 8084
# UI on https://127.0.0.1:8080/web

version: '2'

services:
    remark42:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - SKIP_BACKEND_TEST=true
                # - NODE_ENV=development

        image: umputun/remark42:dev
        container_name: "remark42-dev"
        hostname: "remark42-dev"

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        ports:
         - "8080:8080" # primary rest server
         - "8084:8084" # local oauth2 server

        environment:
            - REMARK_URL=http://127.0.0.1:8080
            - SECRET=12345
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backupang
            - DEBUG=true
            - ADMIN_PASSWD=password
            - AUTH_DEV=true   # activate local oauth "dev"
            - ADMIN_SHARED_ID=dev_user  # set admin flag for default user on local ouath2
            - POSITIVE_SCORE=false # restricts comment's score to be only positive
            - EDIT_TIME=5m # edit window
            - AUTH_ANON=true
            - AUTH_EMAIL_ENABLE=true
        volumes:
            - ./var:/srv/var
