
### find request with tree
GET https://demo.remark42.com/api/v1/find?site=remark&sort=time&format=tree&url=https://radio-t.com/p/2017/12/16/podcast-576/

### find request with plain
GET https://demo.remark42.com/api/v1/find?site=remark&sort=time&format=plain&url=https://radio-t.com/p/2017/12/16/podcast-576/

### last 10 comments
GET https://demo.remark42.com/api/v1/last/50?site=remark

### create comment
POST https://demo.remark42.com/api/v1/comment
Content-Type: application/json

{
	"text": "comment blah http://radio-t.com",
	"user" : {
		"name": "umputun",
		"id": "@umputun",
		"ip": "127.0.0.1"
	},
	"locator": {
		"url": "https://radio-t.com/blah1",
		"site": "remark" 
	}
}

### update comment
PUT https://demo.remark42.com/api/v1/comment/7b88d7a91353ab206cb63cdca18fb26bcb30205b?site=remark&url=https://radio-t.com/blah1
Content-Type: application/json

{
	"text": "edit comment blah http://radio-t.com 12345",
    "summary": "fix blah"
}

### pin comment
PUT https://demo.remark42.com/api/v1/admin/pin/3665976683?site=remark&url=https://radio-t.com/p/2017/12/16/podcast-576/&pin=1

### vote for comment
PUT https://demo.remark42.com/api/v1/vote/3665976683?site=remark&url=https://radio-t.com/p/2017/12/16/podcast-576/&vote=1

### get user info
GET https://demo.remark42.com/api/v1/user

### get comment by id
GET https://demo.remark42.com/api/v1/id/3665976683?site=remark&url=https://radio-t.com/p/2017/12/16/podcast-576/

### get comment by id 2
GET https://demo.remark42.com/api/v1/id/a2ddb8d2f65008ee1a1e3af8df0f26beb042309c?site=remark&url=https://radio-t.com/blah1

### get comment by user id
GET https://demo.remark42.com/api/v1/comments?site=remark&user=umputun

### get counts
GET https://demo.remark42.com/api/v1/count?site=remark&url=https://radio-t.com/p/2017/12/16/podcast-576/

### list commented posts
GET https://demo.remark42.com/api/v1/list?site=remark
