
### find request with tree
GET https://demo.remark42.com/api/v1/find?url=https://radio-t.com/p/2017/12/16/podcast-576/&sort=time&format=tree"

### find request with plain
GET https://demo.remark42.com/api/v1/find?url=https://radio-t.com/p/2017/12/16/podcast-576/&sort=time&format=plain"

### last 10 comments
GET https://demo.remark42.com/api/v1/last/10

### create commnet
POST https://demo.remark42.com/api/v1/comment
Content-Type: application/json

{
	"text": "comment blah http://radio-t.com",
	"user" : {
		"name": "umputun",
		"id": "@umputun",
		"ip": "127.0.0.1"
	},
	"locator": {
		"url": "https://radio-t.com/blah1"
	}
}

### pin comment
PUT https://demo.remark42.com/api/v1/admin/pin/3665976683?url=https://radio-t.com/p/2017/12/16/podcast-576/&pin=1

### vote for comment
PUT https://demo.remark42.com/api/v1/vote/3665976683?url=https://radio-t.com/p/2017/12/16/podcast-576/&vote=1

### get user info
GET https://demo.remark42.com/api/v1/user

### get comment by id
GET https://demo.remark42.com/api/v1/id/3665976683?url=https://radio-t.com/p/2017/12/16/podcast-576/

### get comment by user id
GET https://demo.remark42.com/api/v1/comments?user=grigorybakunov

### get counts
GET https://demo.remark42.com/api/v1/count?url=https://radio-t.com/p/2017/12/16/podcast-576/